### ISSUE TITLE
error

### ISSUE THREAD

**Issue by solomad** [Fildah/chronogg_telebot#1]
Traceback (most recent call last):
  File "bot.py", line 116, in <module>
    with open(current_path + '\\settings\\config.json', 'r') as conf_file:
FileNotFoundError: [Errno 2] No such file or directory: '\\settings\\config.json'
<img width="396" alt="002" src="https://user-images.githubusercontent.com/24777671/61301844-6ed43700-a7ed-11e9-8553-7d6c8353aebe.PNG">

**Comment by Fildah** [comment]
Changed file handling, so it will work right on linux. Just update bot.py
