### ISSUE TITLE
Update Authorization Token

### ISSUE THREAD

**Issue by solomad** [Fildah/chronogg_telebot#3]
No update
<img width="641" alt="007" src="https://user-images.githubusercontent.com/24777671/61502669-7bb77d00-a9dd-11e9-9821-67fd114f6785.PNG">

**Comment by Fildah** [comment]
Hi,

format for /update is /update <token>, so for example command should look something like this /update JWT 234asdedf3se4f...

**Comment by solomad** [comment]
Works
<img width="418" alt="008" src="https://user-images.githubusercontent.com/24777671/61534141-68d19680-aa37-11e9-897d-e4b55ae8c208.PNG">
