### ISSUE TITLE
Auto-spin errors

### ISSUE THREAD

**Issue by solomad** [Fildah/chronogg_telebot#4]
"Bot will coin spin evey day, some time from 18:00-21:00 (time is random)"
Maybe need to make 2-3 tries of auto-spin?
<img width="411" alt="01" src="https://user-images.githubusercontent.com/24777671/61815684-7af66f00-ae53-11e9-9921-6ed998d35da6.PNG">
<img width="450" alt="02" src="https://user-images.githubusercontent.com/24777671/61815793-aa0ce080-ae53-11e9-8cf6-18ccce93a716.PNG">

**Comment by solomad** [comment]
"Bot will coin spin evey day, some time from 18:00-21:00 (time is random)"
I think time from 19:00-21:00 will fix this error

**Comment by Fildah** [comment]
Spin is changed to static 18:05 UTC
